### ISSUE TITLE
[Feature]: Change from "people" to "servings"

### ISSUE THREAD

**Issue by Jajaho** [Slartibartfass2/ingredient_collector#10]
### Is your feature request related to a problem? Please describe

It is unclear that "1 People" refers to two servings.

### Describe the solution you'd like

Change quantities from people to servings.

### Describe alternatives you've considered

Doing the maths in my head - Didn't like it very much, thank you.

### Anything else?

Why did you delete my old issues, wtf?

**Comment by Slartibartfass2** [comment]
Hi, you're refering to the [IngredientGatherer](https://github.com/Slartibartfass2/IngredientGatherer) which is now replaced by this project.
The problem you describe was already solved while developing the new version.
Feel free to test the initial release on Windows.
